---
title: "OCAT Style Guide for R Code"
author: "OCAT Team"
#site: bookdown::bookdown_site
documentclass: book
output:
  #bookdown::gitbook: default
  #css: style_guidance.css
  
  bookdown::gitbook:
    #split_by: chapter
    split_by: none
    css: style_guidance.css
    
  #bookdown::html_book: <!-- including this does not apply the css -->
    #css: style_guidance.css
    
#documentclass: book
  
---

<!-- You need version of R > 3.6.3 and bookdown installed to generate a book -->

```{r mainsetup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(knitr)

#https://bookdown.org/yihui/bookdown/some-tips.html
#https://bookdown.org/yihui/rmarkdown/html-document.html
#https://bookdown.org/yihui/bookdown/output-formats.html


```

<!--# OCAT Style Guide for R Code-->


```{r introduction, child = "01_introduction_v0a.Rmd", echo=FALSE}

# Read in file for introduction - include headings

```


<hr>

```{r naming, child = "02_naming_v0a.Rmd", echo=FALSE}


```

<hr>

```{r organisation, child = "03_organisation_v0a.Rmd", echo=FALSE}


```

<hr>

```{r styling, child = "04_styling_v0a.Rmd", echo=FALSE}


```

<hr>

```{r packages, child = "05_packages_v0a.Rmd", echo=FALSE}


```

